### ISSUE TITLE
ViewModel injection

### ISSUE THREAD

**Issue by Galaxer** [iammert/AndroidArchitecture#1]
In [MovieListFragment](https://github.com/iammert/AndroidArchitecture/blob/master/app/src/main/java/iammert/com/androidarchitecture/ui/main/MovieListFragment.java) I see the following ViewModel injection, however I don't see where you're providing this dependency in any module. How are you injecting this?

```
@Inject
MovieListViewModel movieListViewModel;
```

**Comment by iammert** [comment]
This is how dagger works. When you do constructor injection in your class, You don't need to provide an instance. Dagger do it for you. 

In this case, we provide repository instance in our appmodule. So we can inject into viewmodel by @inject annotation. Dagger checks constructor parameters in viewmodel and check module and provided instances if it can create an instance of that viewmodel. Is it clear?

**Comment by Galaxer** [comment]
Ok, but I thought the way to create the new ViewModel component so that it survives orientation changes and lives only until the activity/fragment is fully destroyed  ([documentation](https://developer.android.com/topic/libraries/architecture/viewmodel.html)) was like following:

`MyViewModel model = ViewModelProviders.of(this).get(MyViewModel.class);`

But wouldn't dagger create a new instance like the this?

`new MovieListViewModel(movieRepository)`

**Comment by iammert** [comment]
You are absolutely right. Future commits will solve this problem. ViewModelFactory class is created for that. I will implement that logic soon.

**Comment by iammert** [comment]
I will keep this open untill I fix this.

**Comment by iammert** [comment]
@Galaxer I fixed that issue. Now viewModels are injected by ViewModelSubComponent and ViewModelProvider.Factory. These classes is created based on googlesamples official architecture.
