### ISSUE TITLE
some issues

### ISSUE THREAD

**Issue by swiftuiux** [iammert/AndroidArchitecture#4]
there`s some issues, one of them is there`s no 

drawable/ic_stars_green_24dp
drawable/ic_language_green_24dp

I had to get rid off it from mark up

**Comment by iammert** [comment]
Did you try clean/rebuild? @ipgaero

**Comment by swiftuiux** [comment]
Thank you

**Comment by rajeevjaiswal** [comment]
@iammert  still this happens. I just browsed the github code and in drawable only placeholder xml is present.

https://github.com/iammert/AndroidArchitecture/tree/master/app/src/main/res/drawable
