### ISSUE TITLE
Could we use Rxjava2 as a substitue of LiveData?

### ISSUE THREAD

**Issue by ysmintor** [iammert/AndroidArchitecture#6]
Since now RxJava2 is popular in many Android projects.

**Comment by iammert** [comment]
Yes, you can. Check out this blog post. https://medium.com/@iammert/offline-app-with-rxjava-2-and-room-ccd0b5c18101

**Comment by ysmintor** [comment]
Oh, I did not see it before. Thanks for your great work.
